### ISSUE TITLE
Consuming too much processor.

### ISSUE THREAD

**Issue by evedostomazi** [bert2/DtmfDetection#12]
I implemented the dll in my project. but only it consumes 20% of my processor.
Is there any way to improve this?
Thank you.

**Comment by bert2** [comment]
I checked the CPU usage of the example application `DtmfDetector` that's part of this repo, but couldn't reproduce your problem. Total CPU usage of _all_ applications was merely above 10% when I ran the live audio analysis (mic in) and fed it some touch tones from my mobile.

I also profiled the live audio analysis and the audio file analysis. As I expected the majority of the time is spent waiting for audio input or reading/decompressing the MP3 file.

Are you sure that DtmfDetection is actually the culprit here?

**Comment by evedostomazi** [comment]
You were right, it was not a dll.
Create a thread that monitors the MasterPeakValue of the microphone input, to display in the progressbar on the screen the volume unit.
Within this thread there was an unnecessary application.doevents.
I removed it and it was all right.
Thanks for the help.
